## 1.5 Combining Data from Multiple Tables

In [22]:
import pandas as pd

## Introduction

Welcome to our introduction to cleaning data! Real-world data is messy. For example, business data is often entered manually by humans. Humans can be somewhat inconsistent in the way that they enter the data. For example, when writing company names, at times they might write Apple, Inc., and at other times they might just write Apple. If we are trying to find the number of times Apple is included in a dataset and only consider the first possibility—Apple, Inc.—we will not obtain a proper count of the number of occurrences of Apple.

Luckily, we can take some steps to clean up datasets. In this lesson, we will go through a synthetic dataset of companies that have been selected for a recent regulatory investigation. For each industry represented in the dataset, we will seek to obtain the average tax revenue produced for the companies within that industry.

## Regulatory Investigation: Tax Revenue Analysis

You will get your first taste for data cleaning by seeing it in action. There are some core concepts of data cleaning that we will lay out later on, but data cleaning ultimately relies on an intimate and careful understanding of the data we are working with. By looking at our data and thinking about what we want to do with it, we can determine how we have to clean it.

First, we load the dataset from the file and take a look at it.

In [23]:
# investigation_companies['tax_revenue'] = investigation_companies['tax_revenue'].apply(lambda row: row.replace("$","").replace(",",""))

In [24]:
# investigation_companies.to_csv('investigation_iran_companies.csv',index = [0])

In [25]:
# investigation_companies.drop(columns = ["Unnamed: 0"], inplace = True)

In [26]:
investigation_companies = pd.read_csv('investigation_iran_companies.csv',index_col = [0])
display(investigation_companies)

,company_name,sector,tax_revenue,number_of_employees,location,ceo_name
0,S&F Co.,Electronics,50000000,300,Tehran,John Smith
1,Ahvazِ Oil Refining,Oil & Gas,1500000000,5000,Ahvaz,Ali Khan
2,Arzan Shargh Trading Ltd.,Trading,3000000,20,Mashhad,Leila Hamidi
3,Amin Pharmaceutical Company - شرکت امین دارویی,Pharma,80000000,200,Tehran,Hamid Rezaei
4,South-Pars Gas Field - میدان گازی جنوب پارس,Energy & Gas,10000000000,2500,Asaluyeh,Ahmad Rahimi
5,Raja Rail Transportation,Logistics,30000000,150,Tehran,Mohammad Gharib
6,بافتِ بزرگ,Textile,5000000,100,Esfahan,Sara Jafari
7,Re&Co,Services,10000000,75,Tehran,Reza Mousavi
8,Sadr Holding,Investment Holding,2000000000,100,Tehran,Seyed Ahmad Hashemi
9,Sepehr Sazeh,Construction,50000000,500,Tehran,Ali Rezaei
10,S@S Food Group,Food,20000000,200,Shiraz,Saeed Azizian
11,Sana Kish,Tourism & Hospitality,5000000,50,Kish Island,Amir Abbas Khadem
12,Sh. Chemical Company,Chemicals,150000000,750,Tehran,Hassan Mirzaei
13,Hammer & Nails,Construction,25000000,150,Tehran,Bahram Nasr
14,Nezam Din & Co.,Legal,2000000,20,Tehran,Mohammad Hosseini
15,Persian Gulf Steel Co.,Steel,500000000,2000,Bandar Abbas,Abdollah Azimi
16,Mahboubi & Sons,Agriculture,10000000,50,Mashhad,Abbas Mahboubi
17,Eshragh Glass Company,Glass,15000000,200,Isfahan,Hossein Rahimi
18,Arta Energy,Renewable Energy,2500000,50,Tehran,Mohammad Mohammadi
19,Zarrin Leather Industries,Leather,7500000,75,Tabriz,Saeed Zarrin
20,Tehran Pharmaceutical Industries,Pharma,120000000,500,Tehran,Mehdi Nouri
21,Shomal Power Plant,Energy,50000000,200,Nowshahr,Ali Fazeli
22,Nikan Insurance,Insurance,8000000,50,Tehran,Ahmad Rahimi
23,Noghrekar,Insurance,30000000,300,Bandar Anzali,Mohammad Ghaderi
24,Bambooshka Design,Graphic Design,500000,5,Tehran,Mitra Alavi
25,Hamyar Software,Software Development,2500000,30,Mashhad,Reza Moradi
26,S&F Co.,Electronics,50000000,300,Tehran,SMITH JOHN
27,ahvazِ oil refining,Oil & Gas,1500000000,5000,Ahvaz,khan ali
28,Arzan Shargh Trading Ltd.,Trading,3000000,20,Mashhad,Hamidi Leila
29,Amin Pharmaceutical,Pharma,80000000,200,Tehran,Rezaei Hamid
30,South-Pars Gas Field,Energy & Gas,10000000000,2500,Asaluyeh,rahimi ahmad
31,Raja Rail,Logistics,30000000,150,Tehran,gharib mohammad
32,بافتِ بزرگ,Textile,5000000,100,Esfahan,Jafari Sara
33,re&co,Services,10000000,75,Tehran,mousavi reza
34,Sadr,Investment,2000000000,100,Tehran,Hashemi Seyed Ahmad
35,sepehr sazeh,Construction,50000000,500,Tehran,rezaei ali
36,S@S Food Group,Food,20000000,200,Shiraz,azizian saeed
37,Sana Kish,Tourism & Hospitality,5000000,50,Kish Island,khadem amiri abbas
38,Sh. Chemical,Chemicals,150000000,750,Tehran,mirzaei hassan
39,Hammer & Nails,Construction,25000000,150,Tehran,nasr bahram
40,Nezam Din,Legal,2000000,20,Tehran,hosseini mohammad
41,Persian Gulf Steel,Steel,500000000,2000,Bandar Abbas,azimi abdollah
42,Mahboubi & Sons,Agriculture,10000000,50,Mashhad,Mahboubi Abbas
43,Eshragh Glass,Glass,15000000,200,Isfahan,rahimi hossein
44,arta energy,Renewable Energy,2500000,50,Tehran,mohammadi mohammad
45,Zarrin Leather,Leather,7500000,75,Tabriz,zarrin saeed
46,tehran pharmaceutical,Pharma,120000000,500,Tehran,nouri mehdi
47,Shomal Power,Energy,50000000,200,Nowshahr,fazeli ali
48,Nikan Insurance,Insurance,8000000,50,Tehran,rahimi ahmad
49,noghrekar,Insurance,30000000,300,Bandar Anzali,ghaderi mohammad
50,bambooshka design,Graphic Design,500000,5,Tehran,alavi mitra
51,hamyar software,Software Development,2500000,30,Mashhad,moradi reza
52,zar & sima,Architecture,5000,1,Shiraz,mohammadi ali

We notice that some companies appear more than once in the dataset, and they appear under slightly different names. For example, we see that row 18 and row 44 both correspond to Arta Energy, and row 3 and row 29 both correspond to Amin Pharmaceutical. We need to eliminate duplicate entries such as these so that we can get the proper value for the average tax revenue corresponding to each industry.

Since this dataset is quite small, we could manually go through it to remove duplicates. However, we will seek to remove duplicates in an automated manner so that you will have the skills to work with larger datasets. 

As a first step, we can simply take care of all instances where the exact same company name occurs more than once in the dataset. We can do this using the drop_duplicates function in pandas as follows:

In [27]:
investigation_companies_dropped = investigation_companies.drop_duplicates(subset = 'company_name')
display(investigation_companies_dropped)
len(investigation_companies_dropped)

,company_name,sector,tax_revenue,number_of_employees,location,ceo_name
0,S&F Co.,Electronics,50000000,300,Tehran,John Smith
1,Ahvazِ Oil Refining,Oil & Gas,1500000000,5000,Ahvaz,Ali Khan
2,Arzan Shargh Trading Ltd.,Trading,3000000,20,Mashhad,Leila Hamidi
3,Amin Pharmaceutical Company - شرکت امین دارویی,Pharma,80000000,200,Tehran,Hamid Rezaei
4,South-Pars Gas Field - میدان گازی جنوب پارس,Energy & Gas,10000000000,2500,Asaluyeh,Ahmad Rahimi
5,Raja Rail Transportation,Logistics,30000000,150,Tehran,Mohammad Gharib
6,بافتِ بزرگ,Textile,5000000,100,Esfahan,Sara Jafari
7,Re&Co,Services,10000000,75,Tehran,Reza Mousavi
8,Sadr Holding,Investment Holding,2000000000,100,Tehran,Seyed Ahmad Hashemi
9,Sepehr Sazeh,Construction,50000000,500,Tehran,Ali Rezaei
10,S@S Food Group,Food,20000000,200,Shiraz,Saeed Azizian
11,Sana Kish,Tourism & Hospitality,5000000,50,Kish Island,Amir Abbas Khadem
12,Sh. Chemical Company,Chemicals,150000000,750,Tehran,Hassan Mirzaei
13,Hammer & Nails,Construction,25000000,150,Tehran,Bahram Nasr
14,Nezam Din & Co.,Legal,2000000,20,Tehran,Mohammad Hosseini
15,Persian Gulf Steel Co.,Steel,500000000,2000,Bandar Abbas,Abdollah Azimi
16,Mahboubi & Sons,Agriculture,10000000,50,Mashhad,Abbas Mahboubi
17,Eshragh Glass Company,Glass,15000000,200,Isfahan,Hossein Rahimi
18,Arta Energy,Renewable Energy,2500000,50,Tehran,Mohammad Mohammadi
19,Zarrin Leather Industries,Leather,7500000,75,Tabriz,Saeed Zarrin
20,Tehran Pharmaceutical Industries,Pharma,120000000,500,Tehran,Mehdi Nouri
21,Shomal Power Plant,Energy,50000000,200,Nowshahr,Ali Fazeli
22,Nikan Insurance,Insurance,8000000,50,Tehran,Ahmad Rahimi
23,Noghrekar,Insurance,30000000,300,Bandar Anzali,Mohammad Ghaderi
24,Bambooshka Design,Graphic Design,500000,5,Tehran,Mitra Alavi
25,Hamyar Software,Software Development,2500000,30,Mashhad,Reza Moradi
27,ahvazِ oil refining,Oil & Gas,1500000000,5000,Ahvaz,khan ali
29,Amin Pharmaceutical,Pharma,80000000,200,Tehran,Rezaei Hamid
30,South-Pars Gas Field,Energy & Gas,10000000000,2500,Asaluyeh,rahimi ahmad
31,Raja Rail,Logistics,30000000,150,Tehran,gharib mohammad
33,re&co,Services,10000000,75,Tehran,mousavi reza
34,Sadr,Investment,2000000000,100,Tehran,Hashemi Seyed Ahmad
35,sepehr sazeh,Construction,50000000,500,Tehran,rezaei ali
38,Sh. Chemical,Chemicals,150000000,750,Tehran,mirzaei hassan
40,Nezam Din,Legal,2000000,20,Tehran,hosseini mohammad
41,Persian Gulf Steel,Steel,500000000,2000,Bandar Abbas,azimi abdollah
43,Eshragh Glass,Glass,15000000,200,Isfahan,rahimi hossein
44,arta energy,Renewable Energy,2500000,50,Tehran,mohammadi mohammad
45,Zarrin Leather,Leather,7500000,75,Tabriz,zarrin saeed
46,tehran pharmaceutical,Pharma,120000000,500,Tehran,nouri mehdi
47,Shomal Power,Energy,50000000,200,Nowshahr,fazeli ali
49,noghrekar,Insurance,30000000,300,Bandar Anzali,ghaderi mohammad
50,bambooshka design,Graphic Design,500000,5,Tehran,alavi mitra
51,hamyar software,Software Development,2500000,30,Mashhad,moradi reza
52,zar & sima,Architecture,5000,1,Shiraz,mohammadi ali

45

We see that there are now 45 rows in our dataset. However, we see that there still some duplicates in the dataset, such as Tehran Pharmaceuticals. We now need to find a way to standardize company names. In other words, we need to make sure that whenever two rows correspond to the same company, there is a company_id that is the same between those two rows, even when the company_name is different. We could make the company_id simply the lower case version of the company_name. This would take care of the Arta Energy case, where we have a row for Arta Energy and a row for arta energy. However, in other cases, this would not be enough. For example, rows 15 and 41 refer to Persian Gulf Steel, but row 15 would become "persian gulf steel & co." and row 41 would become "persian gulf steel."

What if we can use the ceo_name to determine when two companies are in fact the same? This relies on the assumption that no two companies have a CEO with the same name.

In [28]:
investigation_companies_dropped = investigation_companies.drop_duplicates(subset = 'ceo_name')
display(investigation_companies_dropped)
print(len(investigation_companies_dropped))

,company_name,sector,tax_revenue,number_of_employees,location,ceo_name
0,S&F Co.,Electronics,50000000,300,Tehran,John Smith
1,Ahvazِ Oil Refining,Oil & Gas,1500000000,5000,Ahvaz,Ali Khan
2,Arzan Shargh Trading Ltd.,Trading,3000000,20,Mashhad,Leila Hamidi
3,Amin Pharmaceutical Company - شرکت امین دارویی,Pharma,80000000,200,Tehran,Hamid Rezaei
4,South-Pars Gas Field - میدان گازی جنوب پارس,Energy & Gas,10000000000,2500,Asaluyeh,Ahmad Rahimi
5,Raja Rail Transportation,Logistics,30000000,150,Tehran,Mohammad Gharib
6,بافتِ بزرگ,Textile,5000000,100,Esfahan,Sara Jafari
7,Re&Co,Services,10000000,75,Tehran,Reza Mousavi
8,Sadr Holding,Investment Holding,2000000000,100,Tehran,Seyed Ahmad Hashemi
9,Sepehr Sazeh,Construction,50000000,500,Tehran,Ali Rezaei
10,S@S Food Group,Food,20000000,200,Shiraz,Saeed Azizian
11,Sana Kish,Tourism & Hospitality,5000000,50,Kish Island,Amir Abbas Khadem
12,Sh. Chemical Company,Chemicals,150000000,750,Tehran,Hassan Mirzaei
13,Hammer & Nails,Construction,25000000,150,Tehran,Bahram Nasr
14,Nezam Din & Co.,Legal,2000000,20,Tehran,Mohammad Hosseini
15,Persian Gulf Steel Co.,Steel,500000000,2000,Bandar Abbas,Abdollah Azimi
16,Mahboubi & Sons,Agriculture,10000000,50,Mashhad,Abbas Mahboubi
17,Eshragh Glass Company,Glass,15000000,200,Isfahan,Hossein Rahimi
18,Arta Energy,Renewable Energy,2500000,50,Tehran,Mohammad Mohammadi
19,Zarrin Leather Industries,Leather,7500000,75,Tabriz,Saeed Zarrin
20,Tehran Pharmaceutical Industries,Pharma,120000000,500,Tehran,Mehdi Nouri
21,Shomal Power Plant,Energy,50000000,200,Nowshahr,Ali Fazeli
23,Noghrekar,Insurance,30000000,300,Bandar Anzali,Mohammad Ghaderi
24,Bambooshka Design,Graphic Design,500000,5,Tehran,Mitra Alavi
25,Hamyar Software,Software Development,2500000,30,Mashhad,Reza Moradi
26,S&F Co.,Electronics,50000000,300,Tehran,SMITH JOHN
27,ahvazِ oil refining,Oil & Gas,1500000000,5000,Ahvaz,khan ali
28,Arzan Shargh Trading Ltd.,Trading,3000000,20,Mashhad,Hamidi Leila
29,Amin Pharmaceutical,Pharma,80000000,200,Tehran,Rezaei Hamid
30,South-Pars Gas Field,Energy & Gas,10000000000,2500,Asaluyeh,rahimi ahmad
31,Raja Rail,Logistics,30000000,150,Tehran,gharib mohammad
32,بافتِ بزرگ,Textile,5000000,100,Esfahan,Jafari Sara
33,re&co,Services,10000000,75,Tehran,mousavi reza
34,Sadr,Investment,2000000000,100,Tehran,Hashemi Seyed Ahmad
35,sepehr sazeh,Construction,50000000,500,Tehran,rezaei ali
36,S@S Food Group,Food,20000000,200,Shiraz,azizian saeed
37,Sana Kish,Tourism & Hospitality,5000000,50,Kish Island,khadem amiri abbas
38,Sh. Chemical,Chemicals,150000000,750,Tehran,mirzaei hassan
39,Hammer & Nails,Construction,25000000,150,Tehran,nasr bahram
40,Nezam Din,Legal,2000000,20,Tehran,hosseini mohammad
41,Persian Gulf Steel,Steel,500000000,2000,Bandar Abbas,azimi abdollah
42,Mahboubi & Sons,Agriculture,10000000,50,Mashhad,Mahboubi Abbas
43,Eshragh Glass,Glass,15000000,200,Isfahan,rahimi hossein
44,arta energy,Renewable Energy,2500000,50,Tehran,mohammadi mohammad
45,Zarrin Leather,Leather,7500000,75,Tabriz,zarrin saeed
46,tehran pharmaceutical,Pharma,120000000,500,Tehran,nouri mehdi
47,Shomal Power,Energy,50000000,200,Nowshahr,fazeli ali
49,noghrekar,Insurance,30000000,300,Bandar Anzali,ghaderi mohammad
50,bambooshka design,Graphic Design,500000,5,Tehran,alavi mitra
51,hamyar software,Software Development,2500000,30,Mashhad,moradi reza
52,zar & sima,Architecture,5000,1,Shiraz,mohammadi ali

51

This led to the removal of just two rows. This could be due to the fact that some of the CEO names are lower-cased. We create a new column with the lower-cased version of the CEO name and see if we can use this as a basis for removing duplicates; this way we might capture more duplicates.

In [29]:
investigation_companies_dropped = investigation_companies
investigation_companies_dropped['ceo_name_lower'] = investigation_companies_dropped['ceo_name'].str.lower()

In [30]:
investigation_companies_dropped = investigation_companies_dropped.drop_duplicates(subset = 'ceo_name_lower')
display(investigation_companies_dropped)
print(len(investigation_companies_dropped))

,company_name,sector,tax_revenue,number_of_employees,location,ceo_name,ceo_name_lower
0,S&F Co.,Electronics,50000000,300,Tehran,John Smith,john smith
1,Ahvazِ Oil Refining,Oil & Gas,1500000000,5000,Ahvaz,Ali Khan,ali khan
2,Arzan Shargh Trading Ltd.,Trading,3000000,20,Mashhad,Leila Hamidi,leila hamidi
3,Amin Pharmaceutical Company - شرکت امین دارویی,Pharma,80000000,200,Tehran,Hamid Rezaei,hamid rezaei
4,South-Pars Gas Field - میدان گازی جنوب پارس,Energy & Gas,10000000000,2500,Asaluyeh,Ahmad Rahimi,ahmad rahimi
5,Raja Rail Transportation,Logistics,30000000,150,Tehran,Mohammad Gharib,mohammad gharib
6,بافتِ بزرگ,Textile,5000000,100,Esfahan,Sara Jafari,sara jafari
7,Re&Co,Services,10000000,75,Tehran,Reza Mousavi,reza mousavi
8,Sadr Holding,Investment Holding,2000000000,100,Tehran,Seyed Ahmad Hashemi,seyed ahmad hashemi
9,Sepehr Sazeh,Construction,50000000,500,Tehran,Ali Rezaei,ali rezaei
10,S@S Food Group,Food,20000000,200,Shiraz,Saeed Azizian,saeed azizian
11,Sana Kish,Tourism & Hospitality,5000000,50,Kish Island,Amir Abbas Khadem,amir abbas khadem
12,Sh. Chemical Company,Chemicals,150000000,750,Tehran,Hassan Mirzaei,hassan mirzaei
13,Hammer & Nails,Construction,25000000,150,Tehran,Bahram Nasr,bahram nasr
14,Nezam Din & Co.,Legal,2000000,20,Tehran,Mohammad Hosseini,mohammad hosseini
15,Persian Gulf Steel Co.,Steel,500000000,2000,Bandar Abbas,Abdollah Azimi,abdollah azimi
16,Mahboubi & Sons,Agriculture,10000000,50,Mashhad,Abbas Mahboubi,abbas mahboubi
17,Eshragh Glass Company,Glass,15000000,200,Isfahan,Hossein Rahimi,hossein rahimi
18,Arta Energy,Renewable Energy,2500000,50,Tehran,Mohammad Mohammadi,mohammad mohammadi
19,Zarrin Leather Industries,Leather,7500000,75,Tabriz,Saeed Zarrin,saeed zarrin
20,Tehran Pharmaceutical Industries,Pharma,120000000,500,Tehran,Mehdi Nouri,mehdi nouri
21,Shomal Power Plant,Energy,50000000,200,Nowshahr,Ali Fazeli,ali fazeli
23,Noghrekar,Insurance,30000000,300,Bandar Anzali,Mohammad Ghaderi,mohammad ghaderi
24,Bambooshka Design,Graphic Design,500000,5,Tehran,Mitra Alavi,mitra alavi
25,Hamyar Software,Software Development,2500000,30,Mashhad,Reza Moradi,reza moradi
26,S&F Co.,Electronics,50000000,300,Tehran,SMITH JOHN,smith john
27,ahvazِ oil refining,Oil & Gas,1500000000,5000,Ahvaz,khan ali,khan ali
28,Arzan Shargh Trading Ltd.,Trading,3000000,20,Mashhad,Hamidi Leila,hamidi leila
29,Amin Pharmaceutical,Pharma,80000000,200,Tehran,Rezaei Hamid,rezaei hamid
30,South-Pars Gas Field,Energy & Gas,10000000000,2500,Asaluyeh,rahimi ahmad,rahimi ahmad
31,Raja Rail,Logistics,30000000,150,Tehran,gharib mohammad,gharib mohammad
32,بافتِ بزرگ,Textile,5000000,100,Esfahan,Jafari Sara,jafari sara
33,re&co,Services,10000000,75,Tehran,mousavi reza,mousavi reza
34,Sadr,Investment,2000000000,100,Tehran,Hashemi Seyed Ahmad,hashemi seyed ahmad
35,sepehr sazeh,Construction,50000000,500,Tehran,rezaei ali,rezaei ali
36,S@S Food Group,Food,20000000,200,Shiraz,azizian saeed,azizian saeed
37,Sana Kish,Tourism & Hospitality,5000000,50,Kish Island,khadem amiri abbas,khadem amiri abbas
38,Sh. Chemical,Chemicals,150000000,750,Tehran,mirzaei hassan,mirzaei hassan
39,Hammer & Nails,Construction,25000000,150,Tehran,nasr bahram,nasr bahram
40,Nezam Din,Legal,2000000,20,Tehran,hosseini mohammad,hosseini mohammad
41,Persian Gulf Steel,Steel,500000000,2000,Bandar Abbas,azimi abdollah,azimi abdollah
42,Mahboubi & Sons,Agriculture,10000000,50,Mashhad,Mahboubi Abbas,mahboubi abbas
43,Eshragh Glass,Glass,15000000,200,Isfahan,rahimi hossein,rahimi hossein
44,arta energy,Renewable Energy,2500000,50,Tehran,mohammadi mohammad,mohammadi mohammad
45,Zarrin Leather,Leather,7500000,75,Tabriz,zarrin saeed,zarrin saeed
46,tehran pharmaceutical,Pharma,120000000,500,Tehran,nouri mehdi,nouri mehdi
47,Shomal Power,Energy,50000000,200,Nowshahr,fazeli ali,fazeli ali
49,noghrekar,Insurance,30000000,300,Bandar Anzali,ghaderi mohammad,ghaderi mohammad
50,bambooshka design,Graphic Design,500000,5,Tehran,alavi mitra,alavi mitra
51,hamyar software,Software Development,2500000,30,Mashhad,moradi reza,moradi reza
52,zar & sima,Architecture,5000,1,Shiraz,mohammadi ali,mohammadi ali

51

We see that no additional duplicates are being dropped. What is going here? It appears that the first and last names of the CEOs are getting switched at certain points. For example, for one entry of Persian Gulf Steel & Co., the CEO is abdollah azimi, and for the other it is azimi abdollah. We need to make sure the two names of the CEO appear in the same order. To acccomplish this, we can writea function that puts the two names in alphabetical order. This way, for each instance where the two names appear, the two names will appear in the same order.

In [31]:
def put_names_in_order(ceo_name):
  name_list = ceo_name.split() #make the two names of the CEO into a list
  name_list.sort() #Put the names in order
  return ' '.join(name_list) #Put the names back together as a single string

In [32]:
investigation_companies_dropped = investigation_companies
investigation_companies_dropped['ceo_name_lower_ordered'] = investigation_companies_dropped.apply(lambda row: put_names_in_order(row['ceo_name_lower']), axis = 1)

Hopefully, we've now standardized the CEO names. Let's see if we can now use ceo_name_lower_ordered as a basis for dropping duplicates.

In [33]:
investigation_companies_dropped = investigation_companies_dropped.drop_duplicates(subset = 'ceo_name_lower_ordered')
display(investigation_companies_dropped)
print(len(investigation_companies_dropped))

,company_name,sector,tax_revenue,number_of_employees,location,ceo_name,ceo_name_lower,ceo_name_lower_ordered
0,S&F Co.,Electronics,50000000,300,Tehran,John Smith,john smith,john smith
1,Ahvazِ Oil Refining,Oil & Gas,1500000000,5000,Ahvaz,Ali Khan,ali khan,ali khan
2,Arzan Shargh Trading Ltd.,Trading,3000000,20,Mashhad,Leila Hamidi,leila hamidi,hamidi leila
3,Amin Pharmaceutical Company - شرکت امین دارویی,Pharma,80000000,200,Tehran,Hamid Rezaei,hamid rezaei,hamid rezaei
4,South-Pars Gas Field - میدان گازی جنوب پارس,Energy & Gas,10000000000,2500,Asaluyeh,Ahmad Rahimi,ahmad rahimi,ahmad rahimi
5,Raja Rail Transportation,Logistics,30000000,150,Tehran,Mohammad Gharib,mohammad gharib,gharib mohammad
6,بافتِ بزرگ,Textile,5000000,100,Esfahan,Sara Jafari,sara jafari,jafari sara
7,Re&Co,Services,10000000,75,Tehran,Reza Mousavi,reza mousavi,mousavi reza
8,Sadr Holding,Investment Holding,2000000000,100,Tehran,Seyed Ahmad Hashemi,seyed ahmad hashemi,ahmad hashemi seyed
9,Sepehr Sazeh,Construction,50000000,500,Tehran,Ali Rezaei,ali rezaei,ali rezaei
10,S@S Food Group,Food,20000000,200,Shiraz,Saeed Azizian,saeed azizian,azizian saeed
11,Sana Kish,Tourism & Hospitality,5000000,50,Kish Island,Amir Abbas Khadem,amir abbas khadem,abbas amir khadem
12,Sh. Chemical Company,Chemicals,150000000,750,Tehran,Hassan Mirzaei,hassan mirzaei,hassan mirzaei
13,Hammer & Nails,Construction,25000000,150,Tehran,Bahram Nasr,bahram nasr,bahram nasr
14,Nezam Din & Co.,Legal,2000000,20,Tehran,Mohammad Hosseini,mohammad hosseini,hosseini mohammad
15,Persian Gulf Steel Co.,Steel,500000000,2000,Bandar Abbas,Abdollah Azimi,abdollah azimi,abdollah azimi
16,Mahboubi & Sons,Agriculture,10000000,50,Mashhad,Abbas Mahboubi,abbas mahboubi,abbas mahboubi
17,Eshragh Glass Company,Glass,15000000,200,Isfahan,Hossein Rahimi,hossein rahimi,hossein rahimi
18,Arta Energy,Renewable Energy,2500000,50,Tehran,Mohammad Mohammadi,mohammad mohammadi,mohammad mohammadi
19,Zarrin Leather Industries,Leather,7500000,75,Tabriz,Saeed Zarrin,saeed zarrin,saeed zarrin
20,Tehran Pharmaceutical Industries,Pharma,120000000,500,Tehran,Mehdi Nouri,mehdi nouri,mehdi nouri
21,Shomal Power Plant,Energy,50000000,200,Nowshahr,Ali Fazeli,ali fazeli,ali fazeli
23,Noghrekar,Insurance,30000000,300,Bandar Anzali,Mohammad Ghaderi,mohammad ghaderi,ghaderi mohammad
24,Bambooshka Design,Graphic Design,500000,5,Tehran,Mitra Alavi,mitra alavi,alavi mitra
25,Hamyar Software,Software Development,2500000,30,Mashhad,Reza Moradi,reza moradi,moradi reza
37,Sana Kish,Tourism & Hospitality,5000000,50,Kish Island,khadem amiri abbas,khadem amiri abbas,abbas amiri khadem
52,zar & sima,Architecture,5000,1,Shiraz,mohammadi ali,mohammadi ali,ali mohammadi

27

We see that we are down to 27 rows! We have made major headway in removing duplicate companies from this dataset.

We now move on to calculating the average tax revenue for the Insurance industry within the dataset.

In [34]:
investigation_companies_dropped[investigation_companies_dropped['sector'] == 'Insurance']['tax_revenue'].mean()

30000000.0

We run into an error here: 

TypeError: Could not convert $30,000,000 to numeric

How can we address this error? The issue is that the tax_revenue column is of type str (String). To compute the mean of that column, we need to convert the values in it to numeric values. We can do so as follows:

In [35]:
investigation_companies_dropped['tax_revenue'] = investigation_companies_dropped['tax_revenue'].astype(int)

<ipython-input-35-5331f4187fc4>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  investigation_companies_dropped['tax_revenue'] = investigation_companies_dropped['tax_revenue'].astype(int)

In [36]:
We ob

SyntaxError: ignored

In [ ]:
investigation_companies = investigation_companies.drop_duplicates(subset = 'ceo_name')
investigation_companies

Provide key ways in which data must be clean: non-duplicates

##

## Core Concepts In Data Cleaning

Now that we've gotten a taste for data cleaning, we can go through some additional relevant core concepts.


Missing values: Missing values can lead to inaccurate or biased results. Data cleaning involves identifying and addressing missing values, either by imputing them with appropriate estimates or by deleting the affected records.

Duplicate records: Identify and remove any duplicate records in the dataset. Duplicate records can skew results and lead to incorrect conclusions.

Outliers: Outliers are data points that significantly deviate from the rest of the data. Detecting and handling outliers is important to ensure accurate analysis and modeling.

Data transformation: Transforming data involves converting it into a suitable format for analysis. This may involve scaling, normalizing, or encoding categorical variables.

Data consistency: Ensure that data is consistent across all records, particularly when merging or integrating data from multiple sources. This may involve standardizing units, currency, or date formats, as well as reconciling conflicting data points

Data accuracy: Verify that the data is accurate and free from errors, such as incorrect entries or typos. This may involve cross-referencing with other reliable sources or employing domain expertise to identify potential inaccuracies.

#### Using ChatGPT to assist with data cleaning